FRED_API_KEY = "b9aaeb294faa43f487ed8cfb3fc3f474"
ALPHAVANTAGE_API_KEY = "6OBIUJVKMXKRPF8S"
FMP_API_KEY = "8LDzkxTLciWCe7LSf5dyKnQV1Fl8GTIQ"
TRADINGECONOMICS_API_KEY = "e8ebf3567f8b473:l8zd23rsl5xzf55"
